name: Project Tests and coverage

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  frontend-tests:
    runs-on: ubuntu-latest
    name: Frontend Tests and Coverage

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js 18
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: "npm"
          cache-dependency-path: front/package-lock.json

      - name: Install dependencies
        run: npm ci
        working-directory: front

      - name: Run Angular Tests (Jasmine/Karma)
        run: npm run test-coverage
        working-directory: front

      - name: Generate Test Report
        uses: phoenix-actions/test-reporting@v8
        id: test-report-frontend
        if: success() || failure()
        with:
          name: Frontend Tests
          path: front/coverage/test-results.xml
          reporter: java-junit

      - name: Code Coverage Summary Report
        uses: irongut/CodeCoverageSummary@v1.3.0
        id: coverage-report-frontend
        with:
          filename: front/coverage/**/cobertura-coverage.xml
          badge: true
          format: markdown
          hide_branch_rate: false
          hide_complexity: true
          indicators: true
          output: both
          thresholds: "60 80"

      - name: Add Coverage PR Comment
        uses: marocchino/sticky-pull-request-comment@v2
        if: github.event_name == 'pull_request'
        with:
          header: frontend-coverage
          recreate: true
          path: code-coverage-results.md

      - name: Add Test backend report URL in PR Comment
        uses: marocchino/sticky-pull-request-comment@v2
        if: github.event_name == 'pull_request'
        with:
          header: frontend-test
          recreate: true
          message: |
            ### ğŸ› ï¸ Frontend Test Report ğŸ“Š

            ${{ steps.test-report-frontend.outputs.conclusion == 'success' && 'âœ…' || 'âŒ' }} **Statut** : ${{ steps.test-report-frontend.outputs.conclusion }}  
            â±ï¸ **Temps d'exÃ©cution** : ${{ steps.test-report-frontend.outputs.time }} ms  
            ğŸŸ¢ **Tests PassÃ©s** : ${{ steps.test-report-frontend.outputs.passed }}  
            ğŸ”´ **Tests Ã‰chouÃ©s** : ${{ steps.test-report-frontend.outputs.failed }}  
            âšª **Tests IgnorÃ©s** : ${{ steps.test-report-frontend.outputs.skipped }}  

            ğŸ“„ **[Voir le rapport dÃ©taillÃ©]( ${{ steps.test-report-frontend.outputs.runHtmlUrl }} )

  backend-tests:
    runs-on: ubuntu-latest
    name: Backend Tests and Coverage

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          java-version: "11"
          distribution: "temurin"
          cache: maven

      - name: Run tests with Maven
        run: mvn -B test --file back/pom.xml

      - name: Generate Jacoco test report
        run: mvn jacoco:report --file back/pom.xml

      - name: Test Report Backend
        uses: phoenix-actions/test-reporting@v8
        id: test-report-backend
        if: success() || failure()
        with:
          name: Backend Tests
          path: back/target/surefire-reports/*.xml
          reporter: java-junit

      - name: JaCoCo Code Coverage Report
        id: coverage-report-backend
        uses: PavanMudigonda/jacoco-reporter@v5.0
        with:
          coverage_results_path: back/target/site/jacoco/jacoco.xml
          coverage_report_name: Backend Coverage
          coverage_report_title: JaCoCo
          github_token: ${{ secrets.GITHUB_TOKEN }}
          skip_check_run: false
          minimum_coverage: 80
          fail_below_threshold: false
          publish_only_summary: false

      - name: Add Backend Coverage PR Comment
        uses: marocchino/sticky-pull-request-comment@v2
        if: github.event_name == 'pull_request'
        with:
          header: backend-coverage
          recreate: true
          message: |
            ### Backend Coverage report ğŸ“Š

            **Coverage percentage** : ${{ steps.coverage-report-backend.outputs.coverage_percentage }} %
            **Covered lines** : ${{ steps.coverage-report-backend.outputs.covered_lines }}
            **Missed lines** : ${{ steps.coverage-report-backend.outputs.missed_lines }}
            **Total lines** : ${{ steps.coverage-report-backend.outputs.total_lines }}

      - name: Add Test backend report URL in PR Comment
        uses: marocchino/sticky-pull-request-comment@v2
        if: github.event_name == 'pull_request'
        with:
          header: backend-test
          recreate: true
          message: |
            ### ğŸ› ï¸ Backend Test Report ğŸ“Š

            ${{ steps.test-report-backend.outputs.conclusion == 'success' && 'âœ…' || 'âŒ' }} **Statut** : ${{ steps.test-report-backend.outputs.conclusion }}  
            â±ï¸ **Temps d'exÃ©cution** : ${{ steps.test-report-backend.outputs.time }} ms  
            ğŸŸ¢ **Tests PassÃ©s** : ${{ steps.test-report-backend.outputs.passed }}  
            ğŸ”´ **Tests Ã‰chouÃ©s** : ${{ steps.test-report-backend.outputs.failed }}  
            âšª **Tests IgnorÃ©s** : ${{ steps.test-report-backend.outputs.skipped }}  

            ğŸ“„ **[Voir le rapport dÃ©taillÃ©]( ${{ steps.test-report-backend.outputs.runHtmlUrl }} )
